export { default as Logo } from './Logo/Logo.vue'
export { default as PreloaderVerticalizacao } from './PreloaderVerticalizacao/PreloaderVerticalizacao.vue'
export { default as Combobox } from './Combobox/Combobox.vue'
export { default as Card } from './Card/Card.vue'
export { default as Galeria } from './Galeria/Galeria.vue'
export { default as Button } from './Button/Button.vue'
