language: node_js
node_js:
 - lts/*

cache:
 npm: true
 directories:
  - node_modules
  - ~/.cache

branches:
 only:
  - master

install:
 - npm ci

test:
 - npm run test

deploy:
  tag: next
  provider: npm
  email: "desenvolvimento@spurbanismo.sp.gov.br"
  api_key: "NPM_AUTH_TOKEN"
  on:
    tags: true
    repo: SPURB/componentes
  skip_cleanup: 'true'
